### ISSUE TITLE
Update functionality of SHOW_OPERATION_DETAIL authentication method

### ISSUE THREAD

**Issue by romanstrobl** [wultra/powerauth-webflow#314]
The following authentication method configuration is obsolete: `SHOW_OPERATION_DETAIL`. We should remove it from SQL inserts.

This authentication method is still shown implicitly after user authentication is complete, however it has no configuration in database. It was replaced by actual authentication methods `POWERAUTH_TOKEN` and `SMS_KEY`.

**Comment by petrdvorak** [comment]
I believe that `SHOW_OPERATION_DETAIL` still has its place - not all operation types must require 2FA (for example, payment under limit or payment to known user), and you still should let user to decide if he/she approves the operation...

Instead of removing the operation completely, we should introduce testing for `authorize_payment_low_value` operation type.

**Comment by romanstrobl** [comment]
Ok, we can keep it, however it will require changes in the implementation.

**Comment by romanstrobl** [comment]
I believe this issue is obsolete now that Web Flow supports SCA steps with step down and review of the operation.
