### ISSUE TITLE
Add organization context in the login form

### ISSUE THREAD

**Issue by petrdvorak** [wultra/powerauth-webflow#460]
Currently, a user can log in only to the default organization (for example, retail banking). We should also support login to other organizations (for example, SME banking). For this, we need to extend the login form with a "organization context" (picker with "Retail Client" / "Corporate client" values).

This change has the following impact:

- Login form needs to be extended.
- Organization context must be added to the data adapter login call.
- Organization context must be stored by the operation.
- Organization context must be returned in the user info endpoint.

**Comment by romanstrobl** [comment]
I suggest following implementation details:

- It will be possible to configure roles in Next Step server similarly as next steps are defined using a simple configuration table.
  - NS will require at least one `default` role defined.
- Next Step will return list of available roles (at least the default role). Each role has:
  - an identifier (e.g. `RETAIL_CLIENT`)
  - an I18N key (e.g. `role.retailClient`), will be displayed by the UI
  - a flag whether the role is a default role, only one role can have the `is_default` flag
  - an `order` (1, 2, 3...) so that it is clear in which order to display roles in the UI
- It will be possible to set the role when new operation is created.
  - in case no role is set, the default role is used
    - this is useful for case when `USER_ID_ASSIGN` step is used instead of `USERNAME_PASSWORD_AUTH` (there would be no way to choose the role)
- Login form UI will change based on number of roles:
 - 1 role option: no choice of role, same UI as now
 - up to 3 roles: tabs are used to switch the roles
 - more than 3 roles: combobox is used to switch the roles
- Chosen role will be stored as a new column in `ns_operation` table together with the operation.
  - The `USERNAME_PASSWORD_AUTH` can change the role by selecting the tab or combobox.

**Comment by petrdvorak** [comment]
Maybe just a naming issue but "a role" is usually something different.

With a role, one particular user can sign in to a system and act in it under a role. For example, John Doe can login to retail banking as himself, or he can log in to retail banking as an assignee to Jane Smith's account.

What we need is "a system" (or "an organization"), different users can sign in to different organizations. John Doe can sign in to retail banking, Jane Smith can sign in to the corporate banking. John and Jane are in some completely separate user spaces, they have separate credentials and access separate application. We just provide a single place to log in for them.

**Comment by romanstrobl** [comment]
Updated spec:

- It will be possible to configure organizations in Next Step server similarly as next steps are defined using a simple configuration table.
  - NS will require at least one `default` organization defined.
- Next Step will return the list of available organizations (at least the default one). Each organization has:
  - an identifier (e.g. `RETAIL_CLIENT`)
  - an I18N key (e.g. `organization.retailClient`), will be displayed by the UI
  - a flag whether the organization is the default one, only one organization can have the `is_default` flag
  - an `order` (1, 2, 3...) so that it is clear in which order to display organizations in the UI
- When an operation is created the organization is unknown.
  - Initially the `default` organization is pre-selected for the operation.
  - The user can change the organization while logging in (see below).
- Login form UI will change based on number of organizations:
  - 1 organization option: no choice of organization, same UI as now
  - up to 3 organizations: tabs are used to switch the organizations
  - more than 3 organizations: combobox is used to switch the organizations
- Chosen organization will be stored as a new column in `ns_operation` table together with the operation.
  - The user can change the organization in `USERNAME_PASSWORD_AUTH` step by selecting a tab or organization in the combobox.
