### ISSUE TITLE
Enable customization of a default operation

### ISSUE THREAD

**Issue by romanstrobl** [wultra/powerauth-webflow#573]
Using the default login operation is problematic in multiple way (different URL, page refresh issues, hardcoded operation name, hardcoded formData). We should disable default operation and return an error instead.

Fix resolves: https://github.com/wultra/powerauth-webflow/issues/566

**Comment by petrdvorak** [comment]
Adding a comment to the original post - this is not something that we can easily do. The reason is that sometimes, we do not have any system in front of us that could create an operation. As a result, we need a login that will take the OAuth 2.0 attributes (currently, only `client_id` and `scopes` make sense) and creates a correct default operation accordingly.
