### ISSUE TITLE
Two-step selection of account breaks mobile token

### ISSUE THREAD

**Issue by petrdvorak** [wultra/powerauth-webflow#699]
I received a push notification when I was about to select an account from the combo box. I confirmed the operation on mobile, nothing happened on the web and then, after selecting an account, I was prompted for SMS.

Steps to reproduce:

1. Have a user with a mobile token set up.
2. Create a payment.
3. Go through the login (on web and mobile).
=> You are now on the screen with an account selection.
=> You received push message on mobile.

4. Confirm operation on mobile.
5. Select the account.
=> You are prompted for SMS auth.

**Comment by romanstrobl** [comment]
My investigation:
- The payment confirmation step does not yet listen to `/user/topic/authorization` events and does not do polling, so it is not aware of any activity in mobile token.
- The push message about new operation is sent to mobile token in correct moment after the payment is confirmed.
- The root cause is that mobile token does polling and the operation is in pending operation list immediately after the `APPROVAL_SCA` step is chosen, which occurs before payment is confirmed. The operation should not yet be available in pending operations list.

In order to fix the issue, we could:
- change how pending operation list is filtered, however this would make the logic even more complicated
- introduce an SCA operation review step, however, this is something I would prefer to avoid, because it complicates the step definitions and the confirmation logic seems to belong into the `APPROVA_SCA` step
- (preferred option) let Web Flow manage which operations have active mobile token:
  - allow activating mobile token for an operation step and store this value in DB as new column in table `ns_operation_history`, e.g. `mobile_token_active`
  - filter pending operations using value in this column rather than relying on chosen authentication method (which does not allow exact timing, which cause this issue)
  - update current operation history row when mobile token is activated at the right moment:
    - in `SCA_LOGIN` method mobile token is activated during step initialization    
    - in `SCA_APPROVAL` method mobile token is activated after payment confirmation
    - in non-SCA `POWERAUTH_TOKEN` method mobile token is activated during step initialization after user chooses mobile token as an option

In future we will use a new table for mobile token authorizations, so this column can be replaced by rows in this table in the future. Until this functionality is available adding the column seems to be an easy and reliable solution.
