### ISSUE TITLE
Wrong expired error on mobile api

### ISSUE THREAD

**Issue by kober32** [wultra/powerauth-webflow#705]
I let an operation to expire and got  this error:
```
{"status":"ERROR","responseObject":{"code":"ERROR_GENERIC","message":"operation.alreadyFailed"}}
```
which is wrong. Expected error code is `OPERATION_EXPIRED` + message.

This happened to me only once (around `Nov 4, 2019, 3:02 PM GMT+1`) and I couldn't reproduce it.

Such behavior will end in the state, when the operation cannot be canceled or confirmed because a wrong  error code is returned all the time.

**Comment by romanstrobl** [comment]
Ok, we can check at first whether operation is expired, then handle all other cases.

**Comment by romanstrobl** [comment]
This issue discovered two bugs in the backend:
- The error code is invalid because the Exception resolver in Web Flow was catching `OperationAlreadyFailedException` from Next Step package instead of Web Flow package.
- The operation already failed error is a regular error and it was returned because Web Flow checks operation state before checking operation expiration. I seems that for Mobile Token it is better to reverse the order of these checks, so that operation expiration is checked first.

**Comment by romanstrobl** [comment]
I found steps to reproduce the issue:
- Start a payment operation
- Click on Reject in mobile token
- Do nothing in Mobile token
- Wait for operation timeout in web application
- Choose cancellation reason and cancel the operation in mobile token

The operation is already failed, web application previously canceled it due to timeout.
