### ISSUE TITLE
Do not allow sending SMS for expired operations

### ISSUE THREAD

**Issue by petrdvorak** [wultra/powerauth-webflow#740]
Currently, we do not allow verifying SMS OTP for expired operation. However, it is still technically possible to send the SMS OTP, even for expired operation. We should add validation logic to disable this as well.

**Comment by romanstrobl** [comment]
I am not able to reproduce the issue. Most likely it is caused by this problem: https://github.com/wultra/powerauth-webflow/issues/721 In this issue, when Web Socket registration failed, the JavaScript error was not handled which left the application only partially functional. The solution should be to either make Web Sockets registration work or deploy newer build from `develop` branch which catches the JavaScript errors during Web Socket registration.
